
FROM artifacts.corp.xperi.com/docker/node:12-alpine

RUN apk add --no-cache \
  bash \
  curl

WORKDIR /app

ENV PORT 3000
EXPOSE 3000

ENV NODE_ENV test

COPY apidoc.json \
  lint.sh \
  package*.json \
  .babelrc \
  .env-cmdrc \
  .env.* \
  .eslint* \
  .gitignore \
  .prettierrc.json \
  ./

RUN npm install

COPY src src
COPY tests tests

# Build docs
RUN npm run apidoc && \
    npm run openapi

CMD ["npm", "run", "start"]
