# ---------- Base ----------
FROM artifacts.corp.xperi.com/docker/node:12-alpine AS base

RUN apk add --no-cache \
  bash \
  curl

WORKDIR /app

RUN npm install -g migrate-mongo

COPY migrations migrations
COPY ["migrations/package*", "./"]
COPY ["migrate-mongo-config.js", "./"]

RUN npm install

ENV NODE_ENV example

CMD ["migrate-mongo", "status"]
